import { Lato } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "Ayoni",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lato.className}>
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-17857789550"
          strategy="afterInteractive"
        />
        <Script id="google-ads-tag" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17857789550');
          `}
        </Script>
      </head>
      <body className="antialiased">
        <Script
  src="https://www.googletagmanager.com/gtag/js?id=G-G5SWEC7NT4"
  strategy="afterInteractive"
/>

<Script id="google-analytics" strategy="afterInteractive">
  {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-G5SWEC7NT4');
  `}
</Script>

        {children}
      </body>
    </html>
  );
}
